### ISSUE TITLE
Memory issues for point estimates with ate() (estimator="AIPTW,AIPCW")

### ISSUE THREAD

**Issue by jguski** [tagteam/riskRegression#60] opened 2024-08-30 13:13 UTC
Hello! 
I am currently working with your library and it is very helpful to get doubly-robust ATE estimates with AIPTW. However, I have memory problems when trying to fit ate() with estimator="AIPTW,AIPCW" on my dataset, which contains around 47,000 observations. The only way I can get ATE estimates is if I set times to a vector containing only a single point in time, and even then it is only working on an HPC-cluster node with a huge amount of memory. 

In other issues and in the appendix of Ozenne et al. (2018), I read that memory problems can arise when due to influence functions being stored to get confidence intervals. However, I explicitly set `se=FALSE` and `bands=FALSE`, and the problem is encountered while trying to get the point estimate (I also verified this by setting `verbose=TRUE`).

This is probably not a bug at all, but I tried a lot of different configurations by now and would be really interested to understand why exactly the function is so demanding in terms of memory, why it has to be implemented this way and if there may be additional things to try to reduce memory when fitting AIPTW on a large dataset, preferably also for multiple times at once.

Thank you very much in advance!

Kind regards
Jannis

**Comment by tagteam** [comment] 2024-09-02 05:26
Hello Jannis

you did not provide example code to reproduce the problem. I just tried
the following without memory issues:

'''
library(riskRegression)
library(survival)
library(rms)
library(prodlim)
library(data.table)
n <- 50000
set.seed(10)
dt <- sampleData(n, outcome="competing.risks")
dt$X1 <- factor(rbinom(n, prob = c(0.2,0.3) , size = 2), labels = paste0("T",0:2))
fitCR <-  CSC(Hist(time,event)~ X1+X8,data=dt,cause=1)
ateFit2a <- ate(fitCR, data = dt, treatment = "X1", times = c(1,5,10),
                cause = 1, se = FALSE, band = FALSE)
'''

if this works on your machine then my best guess is that you try to
estimate ate at all 47000 time points = overkill?
best Thomas


jguski ***@***.***> writes:

> Hello! 
> I am currently working with your library and it is very helpful to get
> doubly-robust ATE estimates with AIPTW. However, I have memory
> problems when trying to fit ate() with estimator="AIPTW,AIPCW" on my
> dataset, which contains around 47,000 observations. The only way I can
> get ATE estimates is if I set times to a vector containing only a
> single point in time, and even then it is only working on an
> HPC-cluster node with a huge amount of memory.
>
> In other issues and in the appendix of Ozenne et al. (2018), I read
> that memory problems can arise when due to influence functions being
> stored to get confidence intervals. However, I explicitly set
> `se=FALSE` and `bands=FALSE`, and the problem is encountered while
> trying to get the point estimate (I also verified this by setting
> `verbose=TRUE`).
>
> This is probably not a bug at all, but I tried a lot of different
> configurations by now and would be really interested to understand why
> exactly the function is so demanding in terms of memory, why it has to
> be implemented this way and if there may be additional things to try
> to reduce memory when fitting AIPTW on a large dataset, preferably
> also for multiple times at once.
>
> Thank you very much in advance!
>
> Kind regards
> Jannis

-- 
7LL-7 Smile, you don’t own all the problems in the world.

**Comment by jguski** [comment] 2024-09-02 08:18
Hello Thomas,
Thank you for the quick reply and sorry for not providing code. This is a code snippet that reproduces my problem:

'''
library(riskRegression)
library(survival)
library(rms)
library(prodlim)
library(data.table)
n <- 50000
set.seed(10)
dt <- sampleData(n, outcome="survival")
dt$X1 <- factor(rbinom(n, prob = c(0.2,0.3) , size = 1), labels = paste0("T",0:1))

outcome_model <- coxph((Surv(time, event) ~  X1 + X8), data=dt, x=TRUE)

treatment_model <- glm(X1 ~ X7 + X8,
                       data=dt, family="binomial"(link="logit"), x=TRUE)

censoring_model <- coxph((Surv(time, event==0) ~ X1 + X8), data=dt, x=TRUE)

curve <- riskRegression::ate(data = dt,
                            event=outcome_model,
                            treatment=treatment_model,
                            censor=censoring_model,
                            times=c(1,5,10),
                            se=FALSE,
                            band=FALSE,
                            verbose=TRUE,
                            estimator="AIPTW,AIPCW",
                            cause=1)
'''

This quickly depletes all 30GB on my machine. Your code, on the other hand, does work on my computer. However, it uses G-computation for estimation, not AIPTW.

**Comment by tagteam** [comment] 2024-09-02 14:45
thanks, we can now reproduce the problem and will look into it. will
take a few days ...


jguski ***@***.***> writes:

> Hello Thomas,
> Sorry for not providing code. This is a code snippet that reproduces my problem:
>
> '''
> library(riskRegression)
> library(survival)
> library(rms)
> library(prodlim)
> library(data.table)
> n <- 50000
> set.seed(10)
> dt <- sampleData(n, outcome="survival")
> dt$X1 <- factor(rbinom(n, prob = c(0.2,0.3) , size = 1), labels = paste0("T",0:1))
>
> outcome_model <- coxph((Surv(time, event) ~  X1 + X8), data=dt, x=TRUE)
>
> treatment_model <- glm(X1 ~ X7 + X8,
>                        data=dt, family="binomial"(link="logit"), x=TRUE)
>
> censoring_model <- coxph((Surv(time, event==0) ~ X1 + X8), data=dt, x=TRUE)
>
> curve <- riskRegression::ate(data = dt,
>                             event=outcome_model,
>                             treatment=treatment_model,
>                             censor=censoring_model,
>                             times=c(1,5,10),
>                             se=FALSE,
>                             band=FALSE,
>                             verbose=TRUE,
>                             estimator="AIPTW,AIPCW",
>                             cause=1)
> '''
>
> This quickly depletes all 30GB on my machine. Your code, on the other hand, does work on my computer. However, it uses G-computation for estimation, not AIPTW. 

-- 
7LL-7 Smile, you don’t own all the problems in the world.

**Comment by jguski** [comment] 2024-09-02 15:10
Thank you so much!
I am really curious to learn what is behind this.

**Comment by bozenne** [comment] 2024-09-12 10:00
Dear Jannis,

To give a bit of context, I've optimized the implementation of the 'Gformula' estimator but not of the "AIPTW,AIPCW" estimator (as you noticed). So I am not surprised it does not scale well with size of the dataset but it is true that looking more carefully at it the difference is quite dramatic. Roughly speaking the complexity is proportional to the number of observations and the number of unique timepoints. 
- rounding times will facilitate the estimation. This is however introduce ties and lead to an approximate result. However if the rounding is not too agresssive results should be quite close.
In the CRAN version I have noticed that ties where incorrectly handled and I have fixed that in the development version on Github (2024.09.10). So you should get the newer version get use that.

- I have also improved the estimation with only categorical covariates (reduce the data to unique covariates, evaluate risk and influence function, re-expand to match the original data - argument store) but that does not lead to much gain as far as I see.

**Comment by bozenne** [comment] 2024-09-12 10:00
```
library(riskRegression)
library(survival)
library(rms)
library(prodlim)
library(data.table)
library(profvis)

n <- 10000
set.seed(10)
dt <- sampleData(n, outcome="survival")
dt$X1 <- factor(rbinom(n, prob = c(0.2,0.3) , size = 1), labels = paste0("T",0:1))

outcome_model <- coxph((Surv(time, event) ~ X1 + X8), data=dt, x=TRUE)
treatment_model <- glm(X1 ~ X7 + X8, data=dt, family="binomial"(link="logit"), x=TRUE)
censoring_model <- coxph((Surv(time, event==0) ~ X1 + X8), data=dt, x=TRUE)

profvis(
    curve <- riskRegression::ate(data = dt,
                                 event=outcome_model,
                                 treatment=treatment_model,
                                 censor=censoring_model,
                                 times=c(1,5,10),
                                 se=FALSE,
                                 band=FALSE,
                                 verbose=TRUE,
                                 estimator="AIPTW,AIPCW",
                                 cause=1)
) ## 6730 ms, -2475/5495 MB

dt$time.round <- round(dt$time,2)
outcome_model.round <- coxph((Surv(time.round, event) ~ X1 + X8), data=dt, x=TRUE)
censoring_model.round <- coxph((Surv(time.round, event==0) ~ X1 + X8), data=dt, x=TRUE)

profvis(
    curve.round <- riskRegression::ate(data = dt,
                                       event=outcome_model.round,
                                       treatment=treatment_model,
                                       censor=censoring_model.round,
                                       times=c(1,5,10),
                                       se=FALSE,
                                       band=FALSE,
                                       verbose=TRUE,
                                       estimator="AIPTW,AIPCW",
                                       cause=1)
) ## 1820 ms, 0/1560 MB

range(curve.round$meanRisk$estimate - curve$meanRisk$estimate)
## [1] -0.0004232274  0.0005276247
range(100*(curve.round$meanRisk$estimate - curve$meanRisk$estimate)/abs(curve$meanRisk$estimate))
## [1] -0.06600364  0.82031801

```

**Comment by bozenne** [comment] 2024-09-12 10:02
I'll keep look at it a little bit because I am still surprised by how poorly in scale in memory. Maybe I'll find something to be improved (without dramatic change in the implementation)

**Comment by jguski** [comment] 2024-09-13 13:33
Dear Brice,
Thank you very much for the insights and your suggestion. I've actually tested a similar idea, quantile-based discretization of event times. This makes the model a bit more manageable, but it is still very resource-intensive nonetheless. 
Further improvement of the model's scalability would certainly be an asset for your package in the long run. However, please do not feel pressurized by my issue to put a lot of work into this shortly. 

Have a nice weekend!
Jannis

**Comment by bozenne** [comment] 2024-10-21 15:51
I had a closer look and made a few small improvements in the implementation that will lower a bit the memory demand.
On my laptop (memory 16.0 GiB)  I can now run your example with n=25000.

I have also added an extra argument store, that can be set to only evaluate the integral term on a subset of the data at time reducing the memory demand, e.g. store = c(size.split = 1000) will involve 1000 x T instead of n x T matrices (n: number of observations, T number of unique timepoints). With that I can run your example on my laptop:
```
curve <- riskRegression::ate(data = dt,
                             event=outcome_model,
                             treatment=treatment_model,
                             censor=censoring_model,
                             times=c(1,5,10),
                             se=FALSE,
                             band=FALSE,
                             verbose=2,
                             estimator="AIPTW,AIPCW",
                             cause=1,
                             store = c(size.split = 1000))
```

This is available from version 2024.21.10 (only on Github at the time of writing). The documentation of ate has been updated (see details section and examples section).

**Comment by jguski** [comment] 2024-10-29 08:11
Great, thank you for your efforts! It is now working with my example code.

**Comment by bozenne** [comment] 2024-11-03 20:45
Super, I close the issue then.

**Closed as completed by bozenne** 2024-11-03 20:45 UTC
