### ISSUE TITLE
error: Mat::init(): requested size is too large

### ISSUE THREAD

**Issue by andersmik** [tagteam/riskRegression#15] opened 2020-09-16 08:59 UTC
Using the `ate()` function with a dataset of ~600k rows  i run in to the error

>"Mat::init(): requested size is too large; suggest to compile in C++11 mode and/or enable ARMA_64BIT_WORD
>Error in IFlambda0_cpp(tau = tau.hazard_strata, IFbeta = out$IFbeta, newT = new.time,  : 
> Mat::init(): requested size is too large; suggest to compile in C++11 mode and/or enable ARMA_64BIT_WORD 

The machine I'm workning on is the Statistics Denmark server, so memory should not really be the issue (>1TB of RAM). I'm working with riskRegression 2020.02.05 on windows, R version 4.02. As RTools is not installed, compiling in R is not possible, as far as i know.  Is there any other possible solutions? 

```r
#Example
library(prodlim)
library(riskRegression)                
library(survival)
library(data.table)

n=600000

a <- data.frame("risktime"=round(rnorm(n, 500, 50),0),
                "event"=rbinom(n, 1, 0.1),
                "exposure"=factor(rbinom(n,3, 0.3)))

b <- coxph(Surv(risktime, event)~exposure, data=a, x=T)

c <- ate(b, data=a, treatment = "exposure", times=c(500))
```

Regards, Anders

**Comment by bozenne** [comment] 2020-09-16 10:01
What takes a lot of memory is the calculation of the influence function which is required to obtain standard errors/confidence intervals/p-values. I have recently worked on a new version of riskRegression that is more memory efficient and which is available on github (version 2020.08.12 and higher). 

So you have several options:
1- not computing the standard errors/confidence intervals/p-values 
```
c <- ate(b, data=a, treatment = "exposure", times=c(500),
         se = FALSE, band = FALSE)
```
2- Using bootstrap resampling to compute standard errors/confidence intervals/p-values 
```
c <- ate(b, data=a, treatment = "exposure", times=c(500),
         se = TRUE, B = 10000)
```
(note: you may have to convert your dataset to a data.table object to make this works - this should not be necessary in the latest version of riskRegression).
3- Wait that the new version becomes available on Statistics Denmark

**Comment by bozenne** [comment] 2020-09-16 11:00
A bit more details here in case someone is interested. To estimate the variance, ate is:
1- calling iidCox to obtain the iid decomposition of the baseline hazard and regression parameter.
2- calling predictRisk (which in turn call predictCox) to compute the iid decomposition of the average predicted risk.
3- the variance is the sum of squares of this iid decomposition

In term of memory the first step can be quite costly because for each jump time, the influence of each observation on the baseline hazard has to be stored, i.e., this is a n * T matrix for the iid decomposition which grows quickly with the sample size.
The new version avoids to store the iid decomposition and only stores key elements of its that can be assembled (with few operations) to get the iid decomposition at any time point.

To see the difference you can compare:
```
n <- 6000
a <- data.frame("risktime"=round(rnorm(n, 500, 50),0),
                "event"=rbinom(n, 1, 0.1),
                "exposure"=factor(rbinom(n,3, 0.3)))
b <- coxph(Surv(risktime, event)~exposure, data=a, x = TRUE)
iid.new <- iidCox(b, store.iid = "minimal")$iid
iid.old <- iidCox(b, store.iid = "full")$iid
object.size(iid.new) ## 353080 bytes
object.size(iid.old) ## 55167968 bytes
```
Also 
```
str(iid.new$calcIFhazard) ## list of vectors or matrices of size T or n or number of strata * T
```

```
str(iid.old$IFcumhazard) ## n*T matrix
```

and this is why when running ate:
```
profvis::profvis(
c.new <- ate(b, data=a, treatment = "exposure", times=c(500), store.iid = "minimal")
) ## 45 MB
```
```
profvis::profvis(
c.old <- ate(b, data=a, treatment = "exposure", times=c(500), store.iid = "full")
) ## 140 MB
```

the new version handles much better the memory especially when the sample size increases.

**Comment by andersmik** [comment] 2020-09-16 11:27
Thanks for your answer and work on the package. I will try updating to the newest developmental version. 
Using bootstaps, the computation time for my application is quite long.

**Comment by eebea** [comment] 2020-09-21 15:29
Hej @andersmik,
I am facing the same issue, also working on the DST servers (4), but it is taking some time to go make the update available through my channels.  If you are more directly able to upload the update, will it be possible for me to access it as well?
MVH
Emily

**Comment by andersmik** [comment] 2020-09-21 16:21
Yes, I am in contact with Statistics Denmark regarding the installation of
the development version on all FSE R servers. If all goes well it will be
there shortly.

Anders

**Comment by andersmik** [comment] 2020-09-24 12:33
@eebea Development version now on all DST servers in R version 4.02, package name: riskRegressionDev

**Comment by eebea** [comment] 2020-09-25 12:59
@andersmik Thanks very much for the update!  Just in case anyone else is having this problem or following along, I am working on one of the RH hospital servers that has not yet updated to the latest R (we're on 3.6.1), but if you speak with the DST support desk they can make it happen.  Still checking for compatibility.

**Comment by bozenne** [comment] 2020-10-01 13:38
Hi, 

How is it going with the new version? Do you still meet memory issues?

**Comment by andersmik** [comment] 2020-10-02 11:20
So yes, even with the development version I can still run into a memory issue, possibly the development version can calculate the influence function for a bit larger datasets than the current stable version. Imo the best solution for large datasets is using bootstraps and patience (or having a very large RAM).

**Comment by bozenne** [comment] 2020-10-02 16:28
Ok thanks for the feedback. After some investigation I realized that I did not removed the initialization of the super large matrix  when using the new method ... 
It is fixed now and I am able to run your example on my laptop without using too much RAM (<1GB)

> library(riskRegression)
riskRegression version 2020.10.01
> library(survival)
> library(data.table)
data.table 1.13.0 using 32 threads (see ?getDTthreads).  Latest news: r-datatable.com
> memoryConsumed <- function(...){
+     before <- sum(.Internal(gc(verbose = FALSE, reset = TRUE, full = TRUE))[13:14])
+     dots <- list(...)
+     after <- sum(.Internal(gc(verbose = FALSE, reset = FALSE, full = TRUE))[13:14])
+     return(after-before)
+ }
>
> set.seed(10)
> n <- 1e6
> a <- data.table("risktime"=round(rnorm(n, 500, 50),0),
+                 "event"=rbinom(n, 1, 0.1),
+                 "exposure"=factor(rbinom(n,3, 0.3)))
> ## single step
> memoryConsumed(
+     GS <- ate(Surv(risktime, event)~exposure, treatment = "exposure", times = 500, data = a,
+               verbose = FALSE, store.iid = "minimal", product.limit = FALSE, fitter = "coxph")
+ )
[1] 719.8
> ## manually in several steps
> memoryConsumed(
+     e.coxph <- coxph(Surv(risktime, event)~exposure, data = a, x = TRUE, y = TRUE)
+ )
[1] 414.7
> a0 <- copy(a)
> a0$exposure <- factor(0,levels = 0:1)
> a1 <- copy(a)
> a1$exposure <- factor(1,levels = 0:1)
>
> memoryConsumed(
+     risk0 <- predictCox(e.coxph, newdata = a0, average.iid = TRUE, se = FALSE, band = FALSE, store.iid = "minimal+ )times = 500, type = "survival")
[1] 463.5
> memoryConsumed(
+     risk1 <- predictCox(e.coxph, newdata = a1, average.iid = TRUE, se = FALSE, band = FALSE, store.iid = "minimal+ )times = 500, type = "survival")
[1] 446.4

> c(mean(1-risk1$survival), mean(1-risk0$survival), mean(1-risk1$survival) - mean(1-risk0$survival))
sqrt(sum(((1-risk1$survival - mean(1-risk1$survival)) - (1-risk0$survival - mean(1-risk0$survival))  + risk1$survival.average.iid - risk0$survival.average.iid)^2))
[1]  0.067158737  0.067669750 -0.000511013
> sqrt(sum(((1-risk1$survival - mean(1-risk1$survival)) - (1-risk0$survival - mean(1-risk0$survival))  + risk1$survival.average.iid - risk0$survival.average.iid)^2))
[1] 0.0004682588
`

**Closed as completed** 2020-10-29 14:38 UTC
