### ISSUE TITLE
Bootstrap cross-validation gives error when splines included in competing risks regression

### ISSUE THREAD

**Issue by axjadamson** [tagteam/riskRegression#42] opened 2023-02-09 18:24 UTC
Hello! Thank you for this impressive package. I came across this package because I was trying to use bootstrap cross-validation in a competing risks analysis that included splines as predictors. However, I have run into issues doing this.

I followed the instructions on adding non-linear predictors into the model using 'cov1' instead of using the normal model formula. This worked fine to create the full model. However, when it came to the cross-validation, I ran into issues. The error I received was: 

"Errors occured in training models for crossvalidation. 
 Error found in iteration b = 1: 
 Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE, : arguments imply differing number of rows: 81, 205"

This leads me to believe that the 'cov1' matrix that was used to specify the splines in the original model is not updated to account for the lower number of rows of data being used during the cross-validation, which throws up the 'differing number of rows' error. (This is what I suspect - I may be wrong.)

Please find a reproducible example below:

```
library(riskRegression)
library(cmprsk)
library(splines)

data("Melanoma")

# This works:

fgr1<- FGR(Hist(time,status)~age,
           data=Melanoma,cause=1)

score.cv<-Score(list("Fine-Gray"=fgr1),
                formula = Hist(time,status)~1,
                data=Melanoma,times = seq(1000,4000,200),
                split.method="bootcv", 
                B=10)


# This does not work:

ageknots <- model.matrix(~ns(age, knots = 54), Melanoma)[ ,-1]

fgr2<- FGR(Hist(time,status)~cov1(ageknots),
           data=Melanoma,cause=1)

score.cv<-Score(list("Fine-Gray"=fgr2),
                formula = Hist(time,status)~1,
                data=Melanoma,times = seq(1000,4000,200),
                split.method="bootcv", 
                B=10)

```

I have also checked using 'cov1' with the 'poly' command and also ran into the same issues.

As an aside, I was originally looking to use k-fold cross-validation but I can see that there are currently issues with this that are separate to the issue I raise here. If this issue could be sorted out for both methods it would be great!

Thanks,
Alex

**Comment by tagteam** [comment] 2023-02-10 09:45
This is not straightforward to implement in a general way and not currently supported. Your code does not work because the object ageknots is not updated in the subsets of the data during cross-validation. In order to have the crossvalidation algorithm  update the ageknots object, you should write a wrapper function (with corresponding predictRisk S3 method) which integrates the generation of the ageknots into the re-fitting and prediction of risks. Here is what works for your specific model:
```
library(riskRegression)
library(cmprsk)
library(splines)
library(prodlim)
data("Melanoma")
ns_age_fgr <- function(data,knots,...){
    ageknots <- data.frame(model.matrix(~ns(age, knots = knots), data = data)[ ,-1])
    names(ageknots) = paste0("NS_AGE_",1:NCOL(ageknots))
    ## print(names(ageknots))
    data = cbind(data,ageknots)
    fit<- FGR(formula = formula(paste("Hist(time,status)~",paste(names(ageknots),collapse = "+"))),
              data=data,cause=1)
    out = list(fit = fit,call = match.call(),knots = knots)
    class(out) = "ns_age_fgr"
    out
}
predictRisk.ns_age_fgr <- function(object,newdata,times,cause,...){
    ageknots <- data.frame(model.matrix(~ns(age, knots = object$knots), data = newdata)[ ,-1])
    ## print(names(ageknots))
    names(ageknots) = paste0("NS_AGE_",1:NCOL(ageknots))
    newdata = cbind(newdata,ageknots)
    object <- object$fit
    predictRisk(object,newdata = newdata,times = times,cause = cause,...)
}
fgr3<- ns_age_fgr(data=Melanoma,knots = 54)
p3 <- predictRisk(fgr3,times = 1000,newdata = Melanoma[1:100,])
score.cv<-Score(list("Fine-Gray"=fgr3),
                formula = Hist(time,status)~1,
                data=Melanoma,times = seq(1000,4000,200),
                split.method="bootcv", 
                B=10)
# 5-fold seems to work with the github version of riskRegression:
score.k5 <- Score(list("Fine-Gray-NS-Age"=fgr3),
                formula = Hist(time,status)~1,
                data=Melanoma,times = seq(1000,4000,200),
                split.method="cv5", 
                B=1)


```

**Comment by axjadamson** [comment] 2023-02-10 12:58
Thank you so much for this, I will try and implement this with my actual data. I will also install the Github version of riskRegression in order to use k-fold cross validation. 

Would one way to make this generalisable be to inspect the formula call in FGR and write a different method for when cov1 and cov2 are used? I don't know how much time this would take, whether it would work, and whether it is worth doing!

**Comment by axjadamson** [comment] 2023-02-10 17:33
I have managed to extend this to work on my own analysis with multiple splines, thank you very much! I have also installed the Github version of riskRegression in order to get the cross-validation to work. Please can I just verify some things, along with posting a minor issue:

split.method = "cv10"  ---  this will perform 10-fold cross-validation, using 9 folds to train the model and use the trained model to predict in the 10th fold?

B = 1  --- I am pretty sure this is the number of times the 10-fold cross-validation is run (so I want to set it as '1' so that it only runs through the 10 folds once). Is this correct, or do I need to set it at '10' because there are 10 folds?

I must admit, I am not sure in my case what the N and M are referring to. If I change N I can see that the index goes down, but I cannot see what M is doing.  Setting M as bigger than N still works. 

And the issue: 

The output 'split.method$index' gives a function rather than a matrix as specified in the vignette. I can use this function to get the correct matrix by putting 'B' into it.

Thanks!
Alex

**Comment by tagteam** [comment] 2023-02-13 11:40
great that you got it to work. I don't think it is worth to generalize in riskRegression. Instead, the package manager of cmprsk is the right person to implement the splines option somehow. Your guesses regarding the cv10 option seem correct. B=1 is what you want. M is the subsampling size. you are also right that N <= M is not meaningful. M should be smaller than N. We will document the split.method function better in next CRAN version. thanks for pointing this out. I close this issue here, but feel free to send me an email if you want to discuss this further.

**Closed as completed by tagteam** 2023-02-13 11:40 UTC

**Comment by axjadamson** [comment] 2023-02-16 16:57
Okay, makes sense. Thank you so much for everything!
